//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.16 at 07:12:15 PM CET 
//


package eu.visceral.registration.util.measurement;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Measurement package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Measurement
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Measurement }
     * 
     */
    public Measurement createMeasurement() {
        return new Measurement();
    }

    /**
     * Create an instance of {@link Measurement.Metrics }
     * 
     */
    public Measurement.Metrics createMeasurementMetrics() {
        return new Measurement.Metrics();
    }

    /**
     * Create an instance of {@link Measurement.FixedImage }
     * 
     */
    public Measurement.FixedImage createMeasurementFixedImage() {
        return new Measurement.FixedImage();
    }

    /**
     * Create an instance of {@link Measurement.MovingImage }
     * 
     */
    public Measurement.MovingImage createMeasurementMovingImage() {
        return new Measurement.MovingImage();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.DICE }
     * 
     */
    public Measurement.Metrics.DICE createMeasurementMetricsDICE() {
        return new Measurement.Metrics.DICE();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.JACRD }
     * 
     */
    public Measurement.Metrics.JACRD createMeasurementMetricsJACRD() {
        return new Measurement.Metrics.JACRD();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.AUC }
     * 
     */
    public Measurement.Metrics.AUC createMeasurementMetricsAUC() {
        return new Measurement.Metrics.AUC();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.KAPPA }
     * 
     */
    public Measurement.Metrics.KAPPA createMeasurementMetricsKAPPA() {
        return new Measurement.Metrics.KAPPA();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.RNDIND }
     * 
     */
    public Measurement.Metrics.RNDIND createMeasurementMetricsRNDIND() {
        return new Measurement.Metrics.RNDIND();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.ADJRIND }
     * 
     */
    public Measurement.Metrics.ADJRIND createMeasurementMetricsADJRIND() {
        return new Measurement.Metrics.ADJRIND();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.ICCORR }
     * 
     */
    public Measurement.Metrics.ICCORR createMeasurementMetricsICCORR() {
        return new Measurement.Metrics.ICCORR();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.VOLSMTY }
     * 
     */
    public Measurement.Metrics.VOLSMTY createMeasurementMetricsVOLSMTY() {
        return new Measurement.Metrics.VOLSMTY();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.MUTINF }
     * 
     */
    public Measurement.Metrics.MUTINF createMeasurementMetricsMUTINF() {
        return new Measurement.Metrics.MUTINF();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.HDRFDST }
     * 
     */
    public Measurement.Metrics.HDRFDST createMeasurementMetricsHDRFDST() {
        return new Measurement.Metrics.HDRFDST();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.AVGDIST }
     * 
     */
    public Measurement.Metrics.AVGDIST createMeasurementMetricsAVGDIST() {
        return new Measurement.Metrics.AVGDIST();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.MAHLNBS }
     * 
     */
    public Measurement.Metrics.MAHLNBS createMeasurementMetricsMAHLNBS() {
        return new Measurement.Metrics.MAHLNBS();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.VARINFO }
     * 
     */
    public Measurement.Metrics.VARINFO createMeasurementMetricsVARINFO() {
        return new Measurement.Metrics.VARINFO();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.GCOERR }
     * 
     */
    public Measurement.Metrics.GCOERR createMeasurementMetricsGCOERR() {
        return new Measurement.Metrics.GCOERR();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.PROBDST }
     * 
     */
    public Measurement.Metrics.PROBDST createMeasurementMetricsPROBDST() {
        return new Measurement.Metrics.PROBDST();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.SNSVTY }
     * 
     */
    public Measurement.Metrics.SNSVTY createMeasurementMetricsSNSVTY() {
        return new Measurement.Metrics.SNSVTY();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.SPCFTY }
     * 
     */
    public Measurement.Metrics.SPCFTY createMeasurementMetricsSPCFTY() {
        return new Measurement.Metrics.SPCFTY();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.PRCISON }
     * 
     */
    public Measurement.Metrics.PRCISON createMeasurementMetricsPRCISON() {
        return new Measurement.Metrics.PRCISON();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.FMEASR }
     * 
     */
    public Measurement.Metrics.FMEASR createMeasurementMetricsFMEASR() {
        return new Measurement.Metrics.FMEASR();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.ACURCY }
     * 
     */
    public Measurement.Metrics.ACURCY createMeasurementMetricsACURCY() {
        return new Measurement.Metrics.ACURCY();
    }

    /**
     * Create an instance of {@link Measurement.Metrics.FALLOUT }
     * 
     */
    public Measurement.Metrics.FALLOUT createMeasurementMetricsFALLOUT() {
        return new Measurement.Metrics.FALLOUT();
    }

}
